acquisition:
  port:     '/dev/ttyUSB0'
  sample:   60

luftdaten:
  enabled: true
  sensor: ''

influxdb:
  enabled:  true
  url:      'http://xxxx:8086/write?precision=s&db=test'
  #url:      'http://xxxx:8086/write?precision=s&db=test'
  username: 'xxxx'
  password: 'xxxx'
  node:     'xxxx'
  site:     'xxxx'


