acquisition:
  port:     '/dev/ttyUSB0'
  sample:   60
  
site:
  nom: 'site'
  latitude: 45
  longitude: 4.5

luftdaten:
  enabled: true
  sensor: ''

influxdb:
  enabled:  true
  url:      'http://xxxx:8086/write?precision=s&db=luftdaten_test'
  #url:      'http://xxxx:8086/write?precision=s&db=luftdaten_test'
  username: 'xxxx'
  password: 'xxxx'
  node:     'xxxx'
  site:     'test_site'


