acquisition:
  port:     '/dev/ttyUSB0'
  sample:   60

luftdaten:
  enabled: true
  sensor: ''

influxdb:
  enabled:  true
  url:      'http://dmz-aircasting:8086/write?precision=s&db=test'
  #url:      'http://serveur2.mobicitair.fr:8086/write?precision=s&db=test'
  username: 'capto2018'
  password: 'capto_2018 !'
  node:     'raspi-000000009fb800ca'
  site:     'site_test'


